-- All recipes used for this project is by HelloFresh
-- Find their recipes at https://www.hellofresh.com/recipes
USE Pantry;

INSERT INTO Ingredients (ingredient_id, name) VALUES (1, "Sirlon Steak");
INSERT INTO Ingredients (ingredient_id, name) VALUES (2, "Yukon Gold Potatoes");
INSERT INTO Ingredients (ingredient_id, name) VALUES (3, "Sour Cream");
INSERT INTO Ingredients (ingredient_id, name) VALUES (4, "Beef Stock Concentrate");
INSERT INTO Ingredients (ingredient_id, name) VALUES (5, "Kale");
INSERT INTO Ingredients (ingredient_id, name) VALUES (6, "Shallot");
INSERT INTO Ingredients (ingredient_id, name) VALUES (7, "Black Peppercorn");
INSERT INTO Ingredients (ingredient_id, name) VALUES (8, "Salt");
INSERT INTO Ingredients (ingredient_id, name) VALUES (9, "Pepper");
INSERT INTO Ingredients (ingredient_id, name) VALUES (10, "Vegetable Oil");
INSERT INTO Ingredients (ingredient_id, name) VALUES (11, "Butter");
INSERT INTO Ingredients (ingredient_id, name) VALUES (12. "Sweet Potatoes");
INSERT INTO Ingredients (ingredient_id, name) VALUES (13, "Monterey Jack Cheese");
INSERT INTO Ingredients (ingredient_id, name) VALUES (14, "Honey Dijon Dressing");
INSERT INTO Ingredients (ingredient_id, name) VALUES (15, "Onion");
INSERT INTO Ingredients (ingredient_id, name) VALUES (16, "Chicken Cutlet");
INSERT INTO Ingredients (ingredient_id, name) VALUES (17, "Green Beans");
INSERT INTO Ingredients (ingredient_id, name) VALUES (18, "Olive Oil");
INSERT INTO Ingredients (ingredient_id, name) VALUES (19, "Potatoes");
INSERT INTO Ingredients (ingredient_id, name) VALUES (20, "Brocolli");
INSERT INTO Ingredients (ingredient_id, name) VALUES (21, "Frank's Seasoning Blend");
INSERT INTO Ingredients (ingredient_id, name) VALUES (22, "Panko Breadcrumbs");
INSERT INTO Ingredients (ingredient_id, name) VALUES (23, "Honey");
INSERT INTO Ingredients (ingredient_id, name) VALUES (24, "Scallion");
INSERT INTO Ingredients (ingredient_id, name) VALUES (25, "Cooking Oil");
INSERT INTO Ingredients (ingredient_id, name) VALUES (26, "Lemon");
INSERT INTO Ingredients (ingredient_id, name) VALUES (27, "Pork Chop");
INSERT INTO Ingredients (ingredient_id, name) VALUES (28, "Asparagus");
INSERT INTO Ingredients (ingredient_id, name) VALUES (29, "Yellow Onion");
INSERT INTO Ingredients (ingredient_id, name) VALUES (30, "Bold and Savory Steak Spice");
INSERT INTO Ingredients (ingredient_id, name) VALUES (31, "Cucumber");
INSERT INTO Ingredients (ingredient_id, name) VALUES (32, "Garlic Powder");
INSERT INTO Ingredients (ingredient_id, name) VALUES (33, "Pineapple");
INSERT INTO Ingredients (ingredient_id, name) VALUES (34, "White Rice");
INSERT INTO Ingredients (ingredient_id, name) VALUES (35, "Lime");
INSERT INTO Ingredients (ingredient_id, name) VALUES (36, "Cilantro");
INSERT INTO Ingredients (ingredient_id, name) VALUES (37, "Cuban Spice Blend");
INSERT INTO Ingredients (ingredient_id, name) VALUES (38, "Sugar");
INSERT INTO Ingredients (ingredient_id, name) VALUES (39, "Black Pepper");
INSERT INTO Ingredients (ingredient_id, name) VALUES (40, "Tumeric");
INSERT INTO Ingredients (ingredient_id, name) VALUES (41, "Chicken Stock Concentrate");
INSERT INTO Ingredients (ingredient_id, name) VALUES (42, "Shawarma Spice Blend");
INSERT INTO Ingredients (ingredient_id, name) VALUES (43, "Hot Sauce");
INSERT INTO Ingredients (ingredient_id, name) VALUES (44, "Tomato");
INSERT INTO Ingredients (ingredient_id, name) VALUES (45, "Mayonnaise");
INSERT INTO Ingredients (ingredient_id, name) VALUES (46, "Chicken Thighs");
INSERT INTO Ingredients (ingredient_id, name) VALUES (47, "Whole Wheat Pita");
INSERT INTO Ingredients (ingredient_id, name) VALUES (48, "Jasmine Rice");
INSERT INTO Ingredients (ingredient_id, name) VALUES (49, "Rigatoni Pasta");
INSERT INTO Ingredients (ingredient_id, name) VALUES (50, "Garlic");
INSERT INTO Ingredients (ingredient_id, name) VALUES (51, "Tomato Paste");
INSERT INTO Ingredients (ingredient_id, name) VALUES (52, "Parmesan Cheese");
INSERT INTO Ingredients (ingredient_id, name) VALUES (53, "Zucchini");
INSERT INTO Ingredients (ingredient_id, name) VALUES (54, "Italian Pork Sausage");
INSERT INTO Ingredients (ingredient_id, name) VALUES (55, "Cream Cheese");
INSERT INTO Ingredients (ingredient_id, name) VALUES (56, "Chili Flakes");
INSERT INTO Ingredients (ingredient_id, name) VALUES (57, "Roma Tomato");
INSERT INTO Ingredients (ingredient_id, name) VALUES (58, "Ground Turkey");
INSERT INTO Ingredients (ingredient_id, name) VALUES (59, "Sliced Almonds");
INSERT INTO Ingredients (ingredient_id, name) VALUES (60, "Sun-Dried Tomato");
INSERT INTO Ingredients (ingredient_id, name) VALUES (61, "Green Herb Blend");
INSERT INTO Ingredients (ingredient_id, name) VALUES (62, "Spaghetti");
INSERT INTO Ingredients (ingredient_id, name) VALUES (63, "Veggie Stock Concentrate");
INSERT INTO Ingredients (ingredient_id, name) VALUES (64, "Grape Tomato");
INSERT INTO Ingredients (ingredient_id, name) VALUES (65, "Milk");
INSERT INTO Ingredients (ingredient_id, name) VALUES (66, "Old Bay Seasoning");
INSERT INTO Ingredients (ingredient_id, name) VALUES (67, "Flour");
INSERT INTO Ingredients (ingredient_id, name) VALUES (68, "Long Green Pepper");
INSERT INTO Ingredients (ingredient_id, name) VALUES (69, "Demi-Baguette");
INSERT INTO Ingredients (ingredient_id, name) VALUES (70, "Corn");
INSERT INTO Ingredients (ingredient_id, name) VALUES (71, "Carrot");
INSERT INTO Ingredients (ingredient_id, name) VALUES (72, "Southwest Spice Blend");
INSERT INTO Ingredients (ingredient_id, name) VALUES (73, "Flour Tortilla");
INSERT INTO Ingredients (ingredient_id, name) VALUES (74, "Ground Pork");
INSERT INTO Ingredients (ingredient_id, name) VALUES (75, "Shredded Red Cabbage");
INSERT INTO Ingredients (ingredient_id, name) VALUES (76, "Tex-Mex Paste");
INSERT INTO Ingredients (ingredient_id, name) VALUES (77, "Bruseel Sprout");
INSERT INTO Ingredients (ingredient_id, name) VALUES (78, "Pecans");
INSERT INTO Ingredients (ingredient_id, name) VALUES (79, "Fry Seasoning");
INSERT INTO Ingredients (ingredient_id, name) VALUES (80, "Paprika");
INSERT INTO Ingredients (ingredient_id, name) VALUES (81, "Onion Powder");
INSERT INTO Ingredients (ingredient_id, name) VALUES (82, "Cayenne Pepper");
INSERT INTO Ingredients (ingredient_id, name) VALUES (83, "Dijon Mustard");
INSERT INTO Ingredients (ingredient_id, name) VALUES (84, "Apple");
INSERT INTO Ingredients (ingredient_id, name) VALUES (85, "Mixed Greens");
INSERT INTO Ingredients (ingredient_id, name) VALUES (86, "Italian Seasoning");
INSERT INTO Ingredients (ingredient_id, name) VALUES (87, "Seasame Oil");
INSERT INTO Ingredients (ingredient_id, name) VALUES (88, "Soy Sauce");
INSERT INTO Ingredients (ingredient_id, name) VALUES (89, "Button Mushroom");
INSERT INTO Ingredients (ingredient_id, name) VALUES (90, "White Wine Vinegar");
INSERT INTO Ingredients (ingredient_id, name) VALUES (91, "Sriracha");
INSERT INTO Ingredients (ingredient_id, name) VALUES (92, "Ground Beef");
INSERT INTO Ingredients (ingredient_id, name) VALUES (93, "Vegetable Oil");
INSERT INTO Ingredients (ingredient_id, name) VALUES (94, "Ginger");
INSERT INTO Ingredients (ingredient_id, name) VALUES (95, "Chili Pepper");
INSERT INTO Ingredients (ingredient_id, name) VALUES (96, "Curry Powder");
INSERT INTO Ingredients (ingredient_id, name) VALUES (97, "Sweet Thai Chili Sauce");
INSERT INTO Ingredients (ingredient_id, name) VALUES (98, "Bell Pepper");
INSERT INTO Ingredients (ingredient_id, name) VALUES (99, "Chicken Breast");
INSERT INTO Ingredients (ingredient_id, name) VALUES (100, "Coconut Milk");
INSERT INTO Ingredients (ingredient_id, name) VALUES (101, "Shredded Carrot");
INSERT INTO Ingredients (ingredient_id, name) VALUES (102, "Sweet Soy Glaze");
INSERT INTO Ingredients (ingredient_id, name) VALUES (103, "Green Salsa");
INSERT INTO Ingredients (ingredient_id, name) VALUES (104, "Poblano Pepper");
INSERT INTO Ingredients (ingredient_id, name) VALUES (105, "Black Beans");
INSERT INTO Ingredients (ingredient_id, name) VALUES (106, "Mozzarella Cheese");
INSERT INTO Ingredients (ingredient_id, name) VALUES ();

-- https://www.hellofresh.com/recipes/when-steak-met-potatoes-5857fcd16121bb11c124f383
INSERT INTO Recipes (recipe_id, name, serving_size, mins) VALUES (1, "When Steak Met Potatoes", 2, 30);
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (1, 1, "Wash and dry all produce. Preheat oven to 400 degrees. Cut potatoes into ¾-inch-thick wedges. Remove and discard stems and ribs from kale. Chop or tear leaves into 1-inch pieces. Halve, peel, and mince shallot. Use a mallet or heavy pan to pound and crush peppercorns in their bag until coarsely ground.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (2, 1, "Toss potatoes with a drizzle of oil and a pinch of salt and pepper on a baking sheet or baking dish. Roast in oven until tender and lightly browned, 30-35 minutes, tossing halfway through.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (3, 1, "Melt 1 TBSP butter in a large pan over medium heat. Add kale and a splash of water. Cook until leaves are completely wilted and very tender, 4-5 minutes. Season with salt and pepper. Remove from heat, keeping kale in pan.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (4, 1, "Heat a drizzle of oil in a medium pan over medium-high heat. Season steak all over with salt and pepper. Add to pan and cook to desired doneness, 4-7 minutes per side. Remove from pan and set aside to rest, 5 minutes.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (5, 1, "Heat another drizzle of oil in same pan. Add shallot and ¼ tsp crushed peppercorns (more or less to taste). Cook until shallots are soft, 2-3 minutes. Add stock concentrate and ½ cup water. Scrape up any browned bits from pan. Bring to a simmer and let bubble until reduced by half, 2-3 minutes. Remove pan from heat, then stir in half the sour cream.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (6, 1, "Return pan with kale to medium heat. When just warmed, remove from heat and stir in remaining sour cream. Season with salt and pepper. Slice steak against the grain. Divide between plates and serve next to potatoes and kale. Drizzle with sauce.");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (1, 1, 12, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (2, 1, 12, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (3, 1, 4, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (4, 1, 2, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (5, 1, 4, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (6, 1, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (7, 1, 0.5, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (8, 1, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (9, 1, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (10, 1, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (11, 1, 1, "tablespoon");


-- https://www.hellofresh.com/recipes/onion-crunch-chicken-6463f35e8ab1333a8ca24dd0
INSERT INTO Recipes (recipe_id, name, serving_size, mins) VALUES (2, "Onion Crunch Chicken", 2, 30);
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (1, 2, "Adjust rack to middle position (middle and top positions for 4 servings) and preheat oven to 425 degrees. Wash and dry produce.  Peel and dice sweet potatoes into ½-inch pieces.  Using your hands, finely crush crispy fried onions in their bag. (TIP: Once crushed, crispy fried onions should resemble breadcrumbs.) Transfer to a small bowl; stir in Monterey Jack.  Reserve 1 TBSP dressing (2 TBSP for 4 servings) in a second small bowl (you’ll use it in step 3).");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (2, 2, "Place sweet potatoes in a medium pot with enough salted water to cover by 2 inches. Bring to a boil and cook until tender, 15-20 minutes.  Reserve ½ cup potato cooking liquid, then drain and return sweet potatoes to pot. Cover to keep warm.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (3, 2, "Meanwhile, pat chicken* dry with paper towels and season all over with salt and pepper. Place on one side of a baking sheet. (For 4 servings, spread chicken out across entire sheet.)  Evenly spread tops of chicken with a thin layer of reserved dressing. Mound coated sides with onion crust, pressing to adhere (no need to coat the undersides).");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (4, 2, "Toss green beans on empty side of same sheet with a drizzle of olive oil, salt, and pepper. (For 4 servings, add green beans to a second sheet; roast green beans on top rack and chicken on middle rack.)  Roast on middle rack until chicken is cooked through and green beans are browned and tender, 15-20 minutes. TIP: Check chicken periodically—if the crust browns too quickly, loosely cover with foil. Additionally, if green beans finish before chicken, remove from sheet and continue roasting chicken.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (5, 2, "Meanwhile, mash sweet potatoes with sour cream, 2 TBSP butter (4 TBSP for 4 servings), and a big pinch of salt until smooth, adding splashes of reserved potato cooking liquid as needed. Taste and season with salt and pepper.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (6, 2, "Divide mashed sweet potatoes, green beans, and chicken between plates. Serve with remaining dressing on the side. Chicken is fully cooked when internal temperature reaches 165º.");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (12, 2, 2, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (13, 2, 0.25, "cup");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (14, 2, 1.5, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (3, 2, 1.5, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (15, 2, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (16, 2, 10, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (17, 2, 6, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (8, 2, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (9, 2, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (18, 2, 1, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (11, 2, 2, "tablespoon");

-- https://www.hellofresh.com/recipes/buffalo-spiced-crispy-chicken-breasts-5fb7ec0c2d199f61f2235761
INSERT INTO Recipes (recipe_id, name, serving_size, mins) VALUES (3, "Buffalo-Spiced Crispy Chicken Breasts", 2, 30);
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (1, 3, "• Adjust rack to top position (top and middle positions for 4 servings) and preheat oven to 425 degrees. Wash and dry all produce. • Cut broccoli florets into bite-size pieces if necessary. Trim and thinly slice scallions, separating whites from greens. • In a small bowl, combine half the sour cream, ½ tsp Frank’s Seasoning (1 tsp for 4), and a big pinch of salt. (You’ll use the rest of the sour cream and seasoning later.) Stir in water 1 tsp at a time until mixture reaches a drizzling consistency.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (2, 3, "Place 1 TBSP butter (2 TBSP for 4 servings) in a medium microwave safe bowl; microwave until melted, 30-45 seconds. Stir in panko, Monterey Jack, remaining Frank’s Seasoning, and a big pinch of salt and pepper.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (3, 3, "Dice potatoes into ½-inch pieces. • Place in a medium pot with enough salted water to cover by 2 inches. Bring to a boil and cook until tender, 15-20 minutes. • Reserve ½ cup potato cooking liquid, then drain and return empty pot to low heat. Add a drizzle of oil and scallion whites; cook until softened, 1-2 minutes. • Return potatoes to pot. Mash with 1 TBSP butter (2 TBSP for 4 servings) and remaining sour cream until smooth and creamy, adding splashes of reserved potato cooking liquid as needed. Season with salt and pepper. Remove from heat; keep covered until ready to serve.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (4, 3, "While potatoes cook, pat chicken* dry with paper towels and season all over with salt and pepper. • Place on one side of a lightly oiled baking sheet. (For 4 servings, spread chicken out across entire sheet.) Mound tops of chicken breasts with panko mixture, pressing firmly to adhere (no need to coat the undersides).");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (5, 3, "Toss broccoli on opposite side of sheet from chicken with a large drizzle of olive oil and a pinch of salt and pepper. (For 4 servings, add broccoli to a second baking sheet; roast chicken on top rack and broccoli on middle rack.) • Roast on top rack until chicken is golden brown and cooked through and broccoli is slightly crispy, 18-22 minutes. TIP: If broccoli is done before chicken, remove from sheet and continue roasting chicken.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (6, 3, "Transfer roasted broccoli to a large bowl; toss with 1 TBSP butter. • Divide potatoes, chicken, and broccoli between plates. Drizzle chicken with creamy Buffalo sauce and honey (or serve both on the side for dipping). Sprinkle potatoes and chicken with scallion greens and serve.");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (19, 3, 12, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (20, 3, 8, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (21, 3, 0.25, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (22, 3, 0.25, "cup");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (16, 3, 12, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (3, 3, 4, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (23, 3, 2, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (13, 3, 0,25, "cup");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (24, 3, 2, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (25, 3, 2, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (18, 3, 2, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (11, 3, 3, "tablespoon");

-- https://www.hellofresh.com/recipes/w14-mod-steakhouse-style-pork-chops-63f662ff784eb19ff5084813
INSERT INTO Recipes (recipe_id, name, serving_size, mins) VALUES (4, "W14 MOD Steakhouse-Style Pork Chops", 2, 35);
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (1, 4, "Adjust rack to top position (top and middle positions for 4 servings) and preheat oven to 425 degrees. Wash and dry produce. • Dice potatoes into ½-inch pieces. Cut broccoli florets into bite-size pieces if necessary. Halve, peel, and mince half the onion (whole onion for 4). Zest and quarter lemon. Trim and discard woody bottom ends from asparagus; cut crosswise into 1-inch pieces. (Save potatoes for another use.)");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (2, 4, "Toss potatoes on one side of a baking sheet with a drizzle of oil, salt, and pepper. (For 4 servings, spread potatoes out across entire sheet; roast on top rack for 20-25 minutes total.) • Roast on top rack for 5 minutes (you’ll add the broccoli then).");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (3, 4, "Once potatoes have roasted 5 minutes, remove sheet from oven. Carefully toss broccoli on empty side with a drizzle of oil, salt, and pepper. (For 4 servings, leave potatoes roasting and add broccoli to a second baking sheet; roast on middle rack.) • Return to top rack until potatoes are golden brown and broccoli is tender, 15-20 minutes more. Toss asparagus on opposite side of baking sheet from broccoli with a drizzle of oil, salt, and pepper. Roast on top rack until veggies are tender, 15-20 minutes. TIP: If asparagus is done before broccoli, remove from sheet and continue roasting broccoli.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (4, 4, "While veggies roast, pat pork* dry with paper towels; season all over with salt, then coat with as much Steak Spice as will stick. • Heat a drizzle of olive oil in a large pan over medium-high heat. Add pork and cook until browned and cooked through, 4-6 minutes per side. TIP: If crust begins to brown too quickly, reduce heat to medium. • Turn off heat; transfer pork to a cutting board. Wipe out pan.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (5, 4, "Heat a drizzle of olive oil in same pan over medium heat. Add minced onion; cook, stirring, until softened and lightly browned, 3-4 minutes. • Stir in stock concentrate and ¼ cup water (1⁄3 cup for 4 servings). Bring to a simmer and cook until slightly reduced, 2-3 minutes. • Remove from heat and stir in sour cream until combined. Season generously with pepper.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (6, 4, "Toss broccoli with lemon zest. • Thinly slice pork crosswise. • Divide pork, potatoes, and broccoli between plates. Spoon pan sauce over pork. Serve with lemon wedges on the side. Pork is fully cooked when internal temperature reaches 145°.");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (19, 4, 12, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (26, 4, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (27, 4, 10, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (4, 4, 2, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (28, 4, 6, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (29, 4, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (3, 4, 1.5, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (30, 4, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (20, 4, 8, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (8, 4, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (9, 4, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (25, 4, 2, "teaspoon");

-- https://www.hellofresh.com/recipes/pork-chops-and-pineapple-mojo-sauce-68872a5a3947e0d99f170578
INSERT INTO Recipes (recipe_id, name, serving_size, mins) VALUES (5, "Pork Chops & Pineapple Mojo Sauce", 2, 30);
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (1, 5, "Wash and dry produce. Drain pineapple over a small bowl; reserve juice. Trim and dice cucumber into ¼-inch pieces. Halve and peel onion. Dice one-quarter of the onion (half the onion for 4 servings) into ¼-inch pieces; thinly slice another one-quarter of the onion (remaining onion for 4). Roughly chop cilantro. Quarter lime.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (2, 5, "In a small pot, combine rice, 1¼ cups water (2¼ cups for 4 servings), and a pinch of salt. Bring to a boil, then cover and reduce to a low simmer. Cook until rice is tender, 15-20 minutes. Keep covered off heat until ready to serve.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (3, 5, "While rice cooks, in a medium bowl, combine drained pineapple, cucumber, diced onion, half the cilantro, half the garlic powder (you'll use the rest later), 1 TBSP olive oil, ½ tsp sugar, and juice from half the lime (2 TBSP olive oil and 1 tsp sugar for 4 servings). Season with salt and pepper. Refrigerate until ready to serve.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (4, 5, "Pat pork* dry with paper towels and season all over with half the Cuban Spice Blend (you'll use the rest later), salt, and pepper. Heat a large drizzle of oil in a large pan over medium-high heat. Add pork and cook until browned and cooked through, 4-6 minutes per side. TIP: Reduce heat if pork is browning too quickly. Turn off heat; transfer to a cutting board to rest. Wipe out pan.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (5, 5, "Heat a drizzle of oil in pan used for pork over medium-high heat. Add sliced onion and cook, stirring occasionally, until softened, 2-4 minutes. Add pineapple juice, remaining Cuban Spice Blend, remaining garlic powder, and 1 tsp sugar (2 tsp for 4 servings); cook, stirring, until liquid has reduced, 1-2 minutes. Add ¼ cup water (½ cup for 4); cook, stirring, until sauce has thickened, 1-2 minutes. Remove from heat; stir in 2 TBSP butter (4 TBSP for 4) until melted. Add juice from one lime wedge (two wedges for 4). Taste and season with salt and pepper. TIP: If needed, add more water a splash at a time until saucy.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (6, 5, "Slice pork crosswise. Fluff rice with a fork; stir in remaining cilantro. Divide rice, pork, and salad between shallow bowls. Drizzle pork and rice with mojo sauce. Serve.");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (15, 5, 0.5, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (31, 5, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (32, 5, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (33, 5, 4, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (34, 5, 0.75, "cup");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (35, 5, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (36, 5, 0.25, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (27, 5, 10, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (37, 5, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (38, 5, 1.5, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (25, 5, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (39, 5, 1, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (8, 5, 1, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (18, 5, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (11, 5, 2, "tablespoon");

-- https://www.hellofresh.com/recipes/street-cart-style-chicken-bowls-63ecaed802dfc404e006c190
INSERT INTO Recipes (recipe_id, name, serving_size, mins) VALUES (6, "Street Cart-Style Chicken Bowls", 2, 20);
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (1, 6, "In a small pot, melt 1 TBSP butter over medium heat. Stir in ¼ tsp turmeric (½ tsp for 4 servings); cook stirring frequently, until fragrant, 30-60 seconds. • Stir in rice, ¾ cup water (1½ cups for 4), stock concentrate, a big pinch of salt, and pepper. Cover and bring to a boil, then reduce to a simmer. Cook until rice is tender, 15-18 minutes. Keep covered off heat until ready to serve.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (2, 6, "Meanwhile, bring 2 TBSP butter (4 TBSP for 4 servings) to room temperature. Wash and dry produce. • Quarter lemon. Trim and thinly slice scallions, separating whites from greens. Dice tomato into ½-inch pieces. Dice chicken thighs");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (3, 6, "In a small bowl, combine sour cream, mayonnaise, garlic powder, and a squeeze of lemon. Add water 1 tsp at a time until mixture reaches a drizzling consistency. Season with salt and pepper.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (4, 6, "Pat chicken* dry with paper towels; season with Shawarma Spice Blend, salt, and pepper. • Heat a drizzle of oil in a large pan over medium-high heat. Add chicken and scallion whites; cook, stirring occasionally, until chicken is browned and cooked through, 4-6 minutes.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (5, 6, "Toast pitas until softened and warmed through. • Spread with softened butter, then cut each pita into quarters.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (6, 6, "Once rice is done, fluff with a fork; stir in half the scallion greens. Season with salt and pepper to taste. • Divide rice between bowls. Top with chicken and tomato in separate sections; season tomato with a pinch of salt. Drizzle everything with as much white sauce and hot sauce as you like; garnish with remaining scallion greens. Serve with pita and remaining lemon wedges on the side. TIP: We like to scoop up some of the rice, chicken, tomato and sauces with a pita wedge and eat it all in one bite! Chicken is fully cooked when internal temperature reaches 165°.");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (40, 6, 1, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (41, 6, 2, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (26, 6, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (3, 6, 1.5, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (32, 6, 1, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (42, 6, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (43, 6, 1, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (48, 6, 0.5, "cup");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (24, 6, 2, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (44, 6, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (45, 6, 2, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (46, 6, 10, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (47, 6, 2, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (25, 6, 1, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (8, 6, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (9, 6, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (11, 6, 3, "tablespoon");

-- https://www.hellofresh.com/recipes/pork-sausage-rigatoni-rosa-64f8835af6dcf759f5e61093
INSERT INTO Recipes (recipe_id, name, serving_size, mins) VALUES (7, "Pork Sausage Rigatoni Rosa", 2, 20);
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (1, 7, "Wash and dry produce. • Bring a large pot of salted water to a boil. Once water is boiling, add rigatoni; cook, stirring occasionally, until al dente, 9-11 minutes. • Reserve 1 cup pasta cooking water (1½ cups for 4 servings), then drain and set aside. • Meanwhile, trim and halve zucchini lengthwise; slice crosswise into ¼-inch-thick half-moons. Peel and mince or grate garlic.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (2, 7, "While pasta cooks, heat a drizzle of oil in a large pan over medium-high heat. Add zucchini; season with salt and pepper. Cook, stirring occasionally, until browned and tender, 5-6 minutes. Remove pan from heat; transfer zucchini to a plate. • Remove sausage* from casing if necessary; discard casing. Heat another drizzle of oil in same pan over medium-high heat. Add sausage to pan and cook, breaking up meat into pieces, until almost cooked through, 3-4 minutes (it’ll finish cooking in the next step).");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (3, 7, "Stir garlic and tomato paste into pan with sausage; cook until garlic is fragrant, tomato paste is well distributed, and sausage is fully cooked, 1-2 minutes. • Stir in cream cheese, stock concentrate, ½ cup reserved pasta cooking water (ladle straight from the pot if pasta hasn’t finished cooking yet), 1 TBSP butter, ½ tsp sugar, and a pinch of chili flakes to taste. (For 4 servings, use ¾ cup pasta cooking water, 2 TBSP butter, and 1 tsp sugar.) Remove from heat.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (4, 7, "Add drained rigatoni and zucchini to pan with sauce. Stir in half the Parmesan. Season with salt and pepper to taste. TIP: If needed, stir in more reserved pasta cooking water a splash at a time until pasta is coated in a creamy sauce. • Divide between bowls; top with remaining Parmesan and serve. Pork Sausage is fully cooked when internal temperature reaches 160°.");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (49, 7, 6, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (50, 7, 1, "clove");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (51, 7, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (41, 7, 2, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (52, 7, 6, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (53, 7, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (54, 7, 9, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (55, 7, 4, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (56, 7, 1, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (8, 7, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (9, 7, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (25, 7, 2, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (11, 7, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (38, 7, 0.5, "teaspoon");

-- https://www.hellofresh.com/recipes/street-cart-style-turkey-bowls-621e8a34eae5940f43614ace
INSERT INTO Recipes (recipe_id, name, serving_size, mins) VALUES (8, "Street Cart-Style Turkey Bowls", 20);
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (1, 8, "Melt 1 TBSP butter in a small pot over medium heat. Stir in ¼ tsp turmeric (½ tsp for 4 servings) until combined. • Stir in rice, ¾ cup water (1½ cups for 4), and a big pinch of salt and pepper. Bring to a boil, then cover and reduce to a low simmer. Cook until rice is tender, 15-18 minutes. Keep covered off heat until ready to use in step 5.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (2, 8, "Meanwhile, bring 2 TBSP butter (4 TBSP for 4 servings) to room temperature. Wash and dry produce. • Quarter lemon. Trim and thinly slice scallions, separating whites from greens. Dice tomato.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (3, 8, "In a small bowl, combine sour cream, mayonnaise, garlic powder, and a squeeze of lemon juice. Add water 1 tsp at a time until sauce reaches a drizzling consistency. Season with salt and pepper.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (4, 8, "Heat a drizzle of oil in a large pan over medium-high heat. Add scallion whites and cook until fragrant, 30-60 seconds. • Add turkey*, Shawarma Spice, ½ tsp salt (1 tsp for 4 servings), and pepper. Cook, breaking up meat into pieces, until browned and cooked through, 4-6 minutes. • Stir in stock concentrates and ¼ cup water (1⁄3 cup for 4). Reduce heat to medium low and simmer until slightly thickened, 1-2 minutes.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (5, 8, "Fluff rice with a fork; stir in almonds and half the scallion greens. Season with salt and pepper to taste. • Toast pitas. Spread with softened butter; cut each pita into four pieces.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (6, 8, "Divide rice between bowls. Top with turkey and tomato in separate sections; sprinkle tomato with a pinch of salt. Drizzle turkey with hot sauce to taste. Drizzle white sauce over bowls; garnish with remaining scallion greens. Serve with pitas and remaining lemon wedges on the side. TIP: If you like, scoop up some of the rice, turkey, tomato, and sauces with the pita and eat it all in one bite!");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (40, 8, 1, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (24, 8, 2, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (57, 8, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (45, 8, 2, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (58, 8, 10, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (41, 8, 6, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (47, 8, 2, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (48, 8, 0.5, "cup");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (26, 8, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (3, 8, 4, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (32, 8, 1, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (42, 8, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (59, 8, 0.5, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (43, 8, 2, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (8, 8, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (9, 8, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (25, 8, 1, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (11, 8, 3, "tablespoon");

-- https://www.hellofresh.com/recipes/sun-dried-tomato-spaghetti-6231ef8d59a1d65a30536f97
INSERT INTO Recipes (recipe_id, name, serving_size, mins) VALUES(9, "Sun-Dried Tomato Spaghetti", 2, 20);
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (1, 9, "Bring a large pot of salted water to a boil. Wash and dry produce. • Finely chop sun-dried tomatoes. Peel and mince or grate garlic. Halve grape tomatoes lengthwise; place in a small bowl and toss with a drizzle of olive oil, salt, and pepper. Pick parsley leaves from stems; finely chop leaves. Thinly slice chives.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (2, 9, "Once water is boiling, add spaghetti to pot. Cook, stirring occasionally, until al dente, 9-11 minutes. • Reserve 1⁄3 cup pasta cooking water (½ cup for 4 servings), then drain.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (3, 9, "While pasta cooks, heat a large, dry pan over medium-high heat. Add almonds and cook, stirring often, until fragrant and lightly browned, 2-4 minutes. • Turn off heat; transfer to a second small bowl. Wipe out pan.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (4, 9, "Heat a drizzle of olive oil in pan used for almonds over medium heat. Add sun-dried tomatoes and garlic; cook, stirring occasionally, until fragrant, 1-2 minutes. Season with salt and pepper. • Stir in stock concentrate and 1⁄3 cup plain water (½ cup for 4 servings). Bring to a simmer and cook until slightly reduced, 1-2 minutes. • Reduce heat to low and whisk in cream cheese until fully incorporated.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (5, 9, "Stir grape tomatoes into pan with sauce. Add spaghetti, half the Parmesan (save the rest for serving), and 1 TBSP butter (2 TBSP for 4 servings); toss to combine. TIP: If needed, stir in reserved pasta cooking water a splash at a time until pasta is coated in a creamy sauce. • Stir in half the parsley and half the chives. Season with salt and pepper. Turn off heat.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (6, 9, "Divide pasta between bowls. Top with toasted almonds, remaining Parmesan, remaining parsley, and remaining chives. Serve.");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (60, 9, 1.5, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (61, 9, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (62, 9, 6, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (63, 9, 2, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (52, 9, 0.25, "cup");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (50, 9, 1, "clove");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (64, 9, 4, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (59, 9, 0.5, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (55, 9, 2, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (8, 9, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (9, 9, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (18, 9, 2, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (11, 9, 1, "tablespoon");

-- https://www.hellofresh.com/recipes/sweet-corn-poblano-chowder-61a78482d3afc75ab13b9761
INSERT INTO Recipes (recipe_id, name, serving_size, mins) VALUES(10, "Sweet Corn & Poblano Chowder", 2, 40);
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (1, 10, "Adjust rack to top position and preheat oven to 425 degrees. Place 2 TBSP butter (4 TBSP for 4 servings) in a small microwave-safe bowl; set aside to soften (you’ll use it in step 4). Wash and dry produce. • Core, deseed, and dice poblano into ¼-inch pieces. Halve, peel, and finely dice half the shallot (all for 4). Dice potatoes into ½-inch pieces. Drain and rinse corn.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (2, 10, "Melt 2 TBSP plain butter (4 TBSP for 4 servings) in a medium pot over medium-high heat. Add poblano and diced shallot; season with salt and pepper. Cook, stirring, until softened, 2-3 minutes. • Add flour; cook, stirring, until lightly browned, 1 minute.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (3, 10, "Slowly stir milk into pot a splash at a time until fully incorporated. • Stir in 1½ cups water (2½ cups for 4 servings). • Add potatoes, stock concentrates, and half the Old Bay Seasoning (you’ll use more in the next step). Bring to a boil and cook, stirring occasionally, until potatoes are very tender, 15-20 minutes. TIP: To test, pierce one piece with a fork— it should go through easily.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (4, 10, "Meanwhile, combine softened butter, ¼ tsp Old Bay Seasoning, and ¼ tsp sugar until smooth. (For 4 servings, use ½ tsp Old Bay and ½ tsp sugar.) (TIP: If the butter is still cold, microwave for 10 seconds to soften.) Taste and add more Old Bay Seasoning if desired. • Halve baguette lengthwise; spread cut sides with Old Bay butter. Place, cut sides up, on a baking sheet. • Toast on top rack until golden, 3-5 minutes.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (5, 10, "Once potatoes are tender, reduce heat to low and mash with a potato masher or fork to desired consistency. TIP: We recommend mashing until almost smooth, leaving a few small potato pieces for texture. • Stir in cream cheese, corn, and Monterey Jack until fully incorporated and chowder is thick and creamy. If needed, stir in splashes of water until chowder reaches desired consistency (it will be very thick at this point). Season generously with salt and pepper.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (6, 10, "Halve Old Bay toast on a diagonal if desired. • Divide chowder between bowls. Garnish with sour cream. Serve with Old Bay toast on the side.");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (63, 10, 4, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (3, 10, 2, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (65, 10, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (66, 10, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (67, 10, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (6, 10, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (19, 10, 12, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (55, 10, 2, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (68, 10, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (13, 10, 0.25, "cup");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (69, 10, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (70, 10, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (8, 10, 1, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (9, 10, 1, "teaspoon");

-- https://www.hellofresh.com/recipes/crispy-kickin-cayenne-chicken-cutlets-647f3e3302d358ae80bae3c4
INSERT INTO Recipes (recipe_id, name, serving_size, mins) VALUES(11, "Crispy Kickin’ Cayenne Chicken Cutlets", 2, 30);
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (1, 11, "Adjust rack to top position (top and middle positions for 4 servings) and preheat oven to 425 degrees. Wash and dry produce. • Trim, peel, and cut carrots on a diagonal into ½-inch-thick pieces. Trim and thinly slice scallions, separating whites from greens. • In a small bowl, combine half the sour cream, ½ tsp Frank’s Seasoning Blend (1 tsp for 4), and a big pinch of salt. (Be sure to measure the Frank’s Seasoning— you’ll use the rest in the next step.) Stir in water 1 tsp at a time until mixture reaches a drizzling consistency.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (2, 11, "Place 1 TBSP butter (2 TBSP for 4 servings) in a medium microwave-safe bowl; microwave until melted, 30-45 seconds. • Stir in panko, Monterey Jack, remaining Frank’s Seasoning Blend, and a big pinch of salt and pepper.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (3, 11, "Dice potatoes into ½-inch pieces. Place in a medium pot with enough salted water to cover by 2 inches. Bring to a boil; cook until tender, 15-20 minutes. Reserve ½ cup potato cooking liquid, then drain. • Heat a drizzle of oil and scallion whites in empty pot over low heat; cook until softened, 1 minute. Return potatoes to pot; mash with remaining sour cream and 1 TBSP butter (2 TBSP for 4 servings) until smooth and creamy, adding splashes of reserved potato cooking liquid as needed. Season with salt and pepper. Keep covered off heat until ready to serve.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (4, 11, "While potatoes cook, lightly oil a baking sheet. • Toss carrots on one side of sheet with a drizzle of oil, salt, and pepper (for 4 servings, spread out across entire sheet). Roast on top rack for 5 minutes (you’ll add the chicken to the baking sheet then).");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (5, 11, "Meanwhile, pat chicken* dry with paper towels and season with salt and pepper. Mound tops of chicken with panko mixture, pressing firmly to adhere (no need to coat undersides). • Once carrots have roasted 5 minutes, remove sheet from oven. Carefully place chicken, coated sides up, on empty side. (For 4 servings, leave carrots roasting; roast chicken on a second oiled sheet on middle rack.) • Roast on top rack until chicken is golden brown and cooked through and carrots are tender, 15-18 minutes.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (6, 11, "Carefully transfer roasted carrots to a large bowl; add 1 TBSP butter and toss until melted. • Divide carrots, mashed potatoes, and chicken between plates. Drizzle chicken with creamy Buffalo sauce and honey (or serve on the side for dipping). Garnish potatoes and chicken with scallion greens and serve. Chicken is fully cooked when internal temperature reaches 165°.");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (71, 11, 12, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (3, 11, 3, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (22, 11, 0.25, "cup");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (16, 11, 10, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (23, 11, 2, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (24, 11, 2, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (21, 11, 0.25, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (13, 11, 0.25, "cup");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (19, 11, 12, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (8, 11, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (9, 11, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (25, 11, 3, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (11, 11, 3, "tablespoon");

-- https://www.hellofresh.com/recipes/one-pan-santa-fe-pork-tacos-621553e7143a35226e03d7f8
INSERT INTO Recipes (recipe_id, name, serving_size, mins) VALUES(12, "One-Pan Santa Fe Pork Tacos", 2, 20);
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (1, 12, "Wash and dry produce. • Halve, peel, and finely dice onion. Finely chop cilantro. Quarter lemon.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (2, 12, "Heat a drizzle of oil in a large pan over medium-high heat. Add onion and a pinch of salt; cook, stirring occasionally, until slightly softened and lightly browned, 2-3 minutes. • Add pork* and Southwest Spice. Cook, breaking up meat into pieces, until browned and cooked through, 4-6 minutes. TIP: If there’s excess grease in your pan, carefully pour it out.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (3, 12, "While pork cooks, in a large bowl, combine cabbage, mayonnaise, half the cilantro, juice from half the lemon (whole lemon for 4 servings), 1 tsp sugar (2 tsp for 4), and a pinch of salt and pepper.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (4, 12, "Stir Tex-Mex paste into pan with pork mixture until fully coated. Taste and season with salt and pepper. Remove pan from heat. • Wrap tortillas in damp paper towels and microwave until warm and pliable, 30 seconds. • Divide tortillas between plates and fill with pork filling, Monterey Jack, slaw, sour cream, and remaining cilantro. Serve with any remaining lemon wedges on the side.");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (29, 12, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (26, 12, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (72, 12, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (45, 12, 2, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (73, 12, 6, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (3, 12, 2, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (36, 12, 0.25, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (74, 12, 10, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (75, 12, 4, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (76, 12, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (13, 12, 0.25, "cup");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (8, 12, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (9, 12, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (25, 12, 1, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (38, 12, 1, "teaspoon");

-- https://www.hellofresh.com/recipes/pecan-crusted-chicken-6203c3d357b8e37e4638262a
INSERT INTO Recipes (recipe_id, name, serving_size, mins) VALUES(13, "Pecan-Crusted Chicken with Honey Mustard Sauce & Lemony Apple Salad", 2, 30);
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (1, 13, "Adjust rack to middle position and preheat oven to 450 degrees. Wash and dry produce. • Finely chop pecans (or crush in their bag with a heavy pan or rolling pin).");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (2, 13, "Place 1 TBSP butter (2 TBSP for 4 servings) in a medium microwave-safe bowl. Microwave until melted, 30 seconds. • Let cool slightly, then stir in chopped pecans, panko, half the Fry Seasoning (you’ll use the rest later), a drizzle of olive oil, and a pinch of salt and pepper.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (3, 13, "In a small bowl, combine honey, mustard, and mayonnaise.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (4, 13, "Pat chicken* dry with paper towels; season with remaining Fry Seasoning, salt, and pepper. Place on a lightly oiled baking sheet. • Evenly spread tops of chicken with a thin layer of honey mustard sauce (save the rest for serving). Mound with pecan mixture, pressing firmly to adhere (no need to coat the undersides). • Roast on middle rack until crust is golden brown and chicken is cooked through, 15-20 minutes.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (5, 13, "Meanwhile, halve, core, and thinly slice apple. Quarter lemon. • In a large bowl, toss mixed greens and apple with a large drizzle of olive oil and as much lemon juice as you like. Season with salt and pepper.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (6, 13, "Divide chicken and salad between plates. Drizzle chicken with remaining honey mustard sauce. Serve with any remaining lemon wedges on the side.");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (78, 13, 0.5, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (79, 13, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (23, 13, 2, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (16, 13, 10, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (26, 13, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (22, 13, 0.25, "cup");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (83, 13, 2, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (45, 13, 2, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (84, 13, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (85, 13, 2, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (18, 13, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (11, 13, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (8, 13, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (9, 13, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (25, 13, 1, "teaspoon");

INSERT INTO Recipes (recipe_id, name, serving_size, mins) VALUES(14, "Fry Seasoning", null, 5);
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (1, 14, "Mix all ingredients in a bowl");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (80, 14, 2, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (81, 14, 1, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (8, 14, 2, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (39, 14, 1, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (82, 14, 0.5, "teaspoon");

-- https://www.hellofresh.com/recipes/italian-chicken-over-lemony-spaghetti-61f04a680a801820a523ed9c
INSERT INTO Recipes (recipe_id, name, serving_size, mins) VALUES(15, "Italian Chicken over Lemony Spaghetti", 2, 30);
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (1, 15, "Bring a large pot of salted water to a boil. Wash and dry produce. • Trim and quarter zucchini lengthwise; cut crosswise into ½-inch-thick pieces. Peel and mince garlic. Zest and quarter lemon.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (2, 15, "Once water is boiling, add spaghetti to pot. Cook, stirring occasionally, until al dente, 9-11 minutes. • Reserve 1 cup pasta cooking water, then drain. (Keep empty pot handy for step 5.)");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (3, 15, "While pasta cooks, heat a drizzle of olive oil in a large, preferably nonstick, pan over medium-high heat. Add zucchini; cook, stirring occasionally, until browned and softened, 4-6 minutes. Season with salt and pepper. • Turn off heat; transfer to a plate. Wipe out pan.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (4, 15, "Meanwhile, pat chicken* dry with paper towels and season all over with Italian Seasoning, salt, and pepper. • Once zucchini is done, heat a large drizzle of oil in same pan over medium-high heat. Add chicken and cook until browned and cooked through, 3-5 minutes per side. • Turn off heat; transfer to a cutting board to rest. • Once cool enough to handle, slice chicken crosswise.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (5, 15, "Heat a drizzle of olive oil in pot used for spaghetti over medium-high heat. Add garlic, half the lemon zest, and a pinch of chili flakes. Cook, stirring, until fragrant, 20-30 seconds. • Stir in ½ cup reserved pasta cooking water (¾ cup for 4 servings), stock concentrate, and juice from two lemon wedges (four wedges for 4). Simmer until thickened, 1-2 minutes. Turn off heat.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (6, 15, "Add drained spaghetti, zucchini, sour cream, and 1 TBSP butter (2 TBSP for 4 servings) to pot with sauce; toss to coat. • Add half the Parmesan and season with salt and pepper. TIP: If needed, stir in more reserved pasta cooking water a splash at a time until spaghetti is coated in a creamy sauce. • Divide pasta between bowls. Top with chicken, remaining Parmesan, remaining lemon zest, and a pinch of chili flakes if desired. Serve with any remaining lemon wedges on the side.");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (53, 15, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (26, 15, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (16, 15, 10, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (56, 15, 1, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (3, 15, 2, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (50, 15, 1, "clove");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (62, 15, 6, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (86, 15, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (41, 15, 2, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (52, 15, 0.25, "cup");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (18, 15, 2, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (11, 15, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (25, 15, 2, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (8, 15, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (9, 15, null, null);

-- https://www.hellofresh.com/recipes/korean-beef-bibimbap-5ab3b883ae08b53bb4024952
INSERT INTO Recipes (recipe_id, name, serving_size, mins) VALUES(16, "Korean Beef Bibimbap", 2, 30);
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (1, 16, "Wash and dry all produce. Bring 1¼ cups water to a boil in a small pot. Halve zucchini lengthwise; slice into thin half-moons. Trim and thinly slice mushrooms and scallions, keeping scallion greens and whites separate. Peel carrot; using a peeler, shave lengthwise into ribbons. Peel and mince ginger. Mince garlic.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (2, 16, "Once water is boiling, add rice and a pinch of salt to pot. Cover, lower heat, and reduce to a gentle simmer. Cook until tender, 15-20 minutes.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (3, 16, "Toss scallion whites with vinegar and a pinch of salt in a small bowl. Set aside to marinate. In another small bowl, stir together sesame oil, 1½ TBSP sugar, up to half the sriracha, and 1½ TBSP soy sauce (we’ll use the rest of the sriracha and soy sauce later).");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (4, 16, "Heat a drizzle of oil in a large pan over medium-high heat (use a nonstick pan if you have one). Add carrot; season with salt and pepper. Cook, tossing, until tender but still crisp, 3-4 minutes. Remove from pan and set aside. Add another drizzle of oil to pan and repeat with zucchini; remove from pan once cooked. Add mushrooms and another drizzle of oil to pan and cook until tender, 3-5 minutes. Season with salt and pepper. Remove from pan and set aside.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (5, 16, "Heat another drizzle of oil in same pan over medium-high heat. Add garlic and ginger and cook until fragrant, about 30 seconds. Add beef, breaking up meat into pieces. Cook, tossing occasionally, until no longer pink, about 4 minutes. Increase heat to high and continue cooking until browned and crisp, about 3 minutes. Pour in remaining soy sauce and cook, tossing, until mostly evaporated, 1-2 minutes. Season with salt and pepper.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (6, 16, "Divide rice between bowls. Arrange beef, zucchini, carrot, mushrooms, and scallion whites on top. Drizzle with sauce and remaining sriracha (to taste). Sprinkle with scallion greens and serve.");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (53, 16, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (24, 16, 2, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (94, 16, 1, "thumb");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (48, 16, 0.75, "cup");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (87, 16, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (88, 16, 3, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (89, 16, 4, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (71, 16, 6, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (50, 16, 2, "clove");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (90, 16, 5, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (91, 16, 2, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (92, 16, 10, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (8, 16, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (9, 16, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (93, 16, 4, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (38, 16, 1.5, "tablespoon");

-- https://www.hellofresh.com/recipes/thai-coconut-curry-chicken-5fea59f795e99a13fb4bddf0
INSERT INTO Recipes (recipe_id, name, serving_size, mins) VALUES(17, "Thai Coconut Curry Chicken", 2, 30);
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (1, 17, "In a small pot, combine rice, ¾ cup water (1½ cups for 4 servings), and a pinch of salt. Bring to a boil, then cover and reduce to a low simmer. Cook until rice is tender, 15-18 minutes. • Keep covered off heat until ready to serve.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (2, 17, "While rice cooks, wash and dry all produce. • Core, deseed, and dice bell pepper into 1-inch pieces. Zest and quarter lime. Mince cilantro. Thinly slice chili. • Pat chicken* dry with paper towels.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (3, 17, "Heat a large drizzle of oil in a medium pan over medium-high heat (use a large pan for 4 servings). Add bell pepper and a big pinch of salt. Cook, stirring occasionally, 5 minutes.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (4, 17, "Add chicken, another large drizzle of oil, and a big pinch of salt to pan with bell pepper. Cook, stirring occasionally, until chicken is lightly browned, 3-4 minutes (it’ll finish cooking in the next step). • Stir in half the curry powder (all for 4 servings); cook for 1 minute.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (5, 17, "Thoroughly shake coconut milk in container before opening • Stir ⅔ cup coconut milk (1⅓ cups for 4 servings), chili sauce, stock concentrate, juice from half the lime, and 1 tsp sugar (2 tsp for 4) into pan with chicken mixture. Bring to a simmer, then reduce heat to medium low. Simmer until sauce is thickened, bell pepper is tender, and chicken is cooked through, 4-6 minutes. • Taste and season with salt and more lime juice if desired. Turn off heat.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (6, 17, "Fluff rice with a fork; stir in lime zest, half the cilantro, and 1 TBSP butter (2 TBSP for 4 servings). Season with salt and pepper. • Divide rice between shallow bowls and top with coconut curry chicken, remaining cilantro, and a pinch of chili if desired. Serve with any remaining lime wedges on the side.");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (48, 17, 0.5, "cup");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (35, 17, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (95, 17, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (96, 17, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (97, 17, 1, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (98, 17, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (36, 17, 0.25, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (99, 17, 10, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (100, 17, 5, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (41, 17, 2, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (93, 17, 4, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (11, 17, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (8, 17, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (9, 17, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (38, 17, 1, "teaspoon");

-- https://www.hellofresh.com/recipes/sesame-soy-beef-bowls-5fd0e263d3f63548ac094b5b
INSERT INTO Recipes (recipe_id, name, serving_size, mins) VALUES(18, "Sesame Soy Beef Bowls", 2, 20);
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (1, 18, "Wash and dry produce. • In a small pot, combine rice, 1¼ cups water (2¼ cups for 4 servings), and a pinch of salt. Bring to a boil, then cover and reduce to a low simmer. Cook until rice is tender, 15-18 minutes. Keep covered off heat until ready to serve. • Meanwhile, trim and thinly slice scallions, separating whites from greens. • In a small bowl, combine mayonnaise with sriracha to taste. Stir in water 1 tsp at a time until mixture reaches a drizzling consistency. Season with salt and pepper.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (2, 18, "Heat half the sesame oil (you’ll use the rest in the next step) in a large pan over medium-high heat. Add carrots and scallion whites; cook, stirring occasionally, until slightly softened, 1-2 minutes. Season with salt, pepper, and a pinch of sugar. • Transfer to a second small bowl and cover to keep warm.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (3, 18, "Heat a drizzle of oil in pan used for carrots over medium high heat. Add beef* and cook, breaking up meat into pieces, until browned, 3-5 minutes. TIP: If there’s excess grease in your pan, carefully pour it out. • Stir in sweet soy glaze, half the vinegar (all for 4 servings), and remaining sesame oil. Bring to a simmer and cook until sauce has thickened and beef is cooked through, 2-3 minutes. • Remove from heat. Taste and season with salt and pepper if desired.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (4, 18, "Fluff rice with a fork and stir in 1 TBSP butter (2 TBSP for 4 servings); season with salt and pepper. • Divide rice between bowls; top with carrots and sesame soy beef. Drizzle with sriracha mayo and sprinkle with scallion greens. Serve.");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (24, 18, 4, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (91, 18, 2, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (101, 18, 8, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (102, 18, 8, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (48, 18, 1.5, "cup");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (45, 18, 4, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (87, 18, 2, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (92, 18, 20, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (90, 18, 5, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (8, 18, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (9, 18, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (93, 18, 1, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (11, 18, 2, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (38, 18, 1, "teaspoon");

-- https://www.hellofresh.com/recipes/salsa-verde-enchiladas-5e838ed26d09bc180e655e61
INSERT INTO Recipes (recipe_id, name, serving_size, mins) VALUES(19, "Salsa Verde Enchiladas", 2, 35);
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (1, 19, "Adjust rack to top position and preheat oven to 475 degrees. Wash and dry all produce. Core, deseed, and dice poblano. Finely dice tomato. Trim and thinly slice scallions, separating whites from greens. Drain beans over a small bowl, reserving liquid. Thinly slice chili.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (2, 19, "Heat a drizzle of oil in a large pan over medium-high heat. Add poblano and cook until just softened, 3-4 minutes.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (3, 19, "Meanwhile, reserve ½ tsp Southwest Spice (1 tsp for 4 servings) in a second small bowl. Once poblano is just softened, add tomato, scallion whites, half the beans (you’ll use the rest later), 2 TBSP reserved bean liquid, and remaining Southwest Spice to pan. Cook, stirring, until fragrant and warmed through, 2-3 minutes. Season with salt and pepper.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (4, 19, "Heat a large drizzle of oil in a small pot over medium-high heat. Add remaining beans and cook, stirring, until slightly softened, 2-3 minutes. Add 3 TBSP reserved bean liquid (⅓ cup for 4 servings; you may have some left over). Simmer until warmed through, 1-2 minutes. Reduce heat to low and stir in 1 TBSP butter (2 TBSP for 4). Turn off heat; mash with a potato masher or fork until mostly smooth. Season with plenty of salt and pepper.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (5, 19, "Spread tortillas with mashed beans. Place a small amount of filling on one half of each tortilla. Roll up tortillas, starting with filled side, and place seam sides down in an 8-by-11-inch baking dish or ovenproof pan. (For 4 servings, place in a 9-by-13-inch baking dish or two smaller ones.) Spoon enough salsa over to generously coat (you may have some left over). Sprinkle with Monterey Jack. Bake on top rack until salsa is bubbly and cheese melts, 3-5 minutes.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (6, 19, "Meanwhile, add sour cream to bowl with reserved Southwest Spice. Stir in warm water 1 tsp at a time until mixture reaches a drizzling consistency. Season with salt and pepper. Top baked enchiladas with crema, scallion greens, and as much chili as you like. Divide between plates and serve.");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (24, 19, 2, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (57, 19, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (72, 19, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (103, 19, 7.06, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (3, 19, 2, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (104, 19, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (105, 19, 13.4, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (73, 19, 6, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (13, 19, 0.25, "cup");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (95, 19, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (8, 19, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (9, 19, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (11, 19, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (93, 19, 1, "tablespoon");

-- https://www.hellofresh.com/recipes/italian-chicken-pepper-sandos-6075d61c38625b79a415ba8b
INSERT INTO Recipes (recipe_id, name, serving_size, mins) VALUES(20, "Italian Chicken & Pepper Sandos", 2, 35);
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (1, 20, "Adjust racks to top and middle positions and preheat oven to 450 degrees. Wash and dry all produce. • Cut potatoes into ½-inch-thick wedges. Halve, peel, and thinly slice onion. Halve, core, and thinly slice green pepper into strips.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (2, 20, "Toss potatoes on a baking sheet with a large drizzle of oil, salt, and pepper. Roast on top rack until golden brown and crispy, 20-25 minutes. • Meanwhile, in a small bowl, combine mayonnaise, sour cream, and half the garlic powder (you’ll use the rest later). Season with salt and pepper.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (3, 20, "Heat a large drizzle of oil in a large pan over medium-high heat. Add onion and green pepper; cook, stirring occasionally, until softened and lightly browned, 5-7 minutes. Season with salt and pepper. • Turn off heat; transfer to a plate.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (4, 20, "While veggies cook, in a second small microwave-safe bowl, combine 2 TBSP butter (4 TBSP for 4 servings) and remaining garlic powder; microwave until butter is just softened, 10-15 seconds. Stir to combine and season with salt and pepper; set aside. • Slice baguettes lengthwise, stopping before you get all the way through; spread garlic butter onto cut sides. Place cut sides up on a second baking sheet. • Toast on middle rack until golden, 2-3 minutes.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (5, 20, "While garlic buns toast, pat chicken* dry with paper towels; season generously with salt and pepper. • Heat a large drizzle of oil in pan used for veggies over medium-high heat. Add chicken and Italian Seasoning; cook, stirring, until chicken is browned and cooked through, 4-6 minutes. • Stir in stock concentrate and 2 TBSP water (4 TBSP for 4 servings). Season with salt and pepper. • Return cooked veggies to pan; stir to combine. Turn off heat.");
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES (6, 20, "Spread bottom halves of toasted garlic buns with half the garlic sauce. Top with chicken and veggie mixture, then sprinkle with mozzarella. Return to middle rack until cheese melts, 2-3 minutes. • Divide sandos and potatoes between plates. Serve with remaining garlic sauce on the side.");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (2, 20, 12, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (68, 20, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (3, 20, 2, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (99, 20, 10, "ounce");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (41, 20, 2, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (106, 20, 0.5, "cup");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (29, 20, 1, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (45, 20, 2, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (32, 20, 1, "teaspoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (86, 20, 1, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (69, 20, 2, "unit");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (8, 20, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (9, 20, null, null);
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (11, 20, 2, "tablespoon");
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES (25, 20, 2, "tablespoon");


/*
INSERT INTO Recipes (recipe_id, name, serving_size, mins) VALUES();
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES ();
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES ();
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES ();
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES ();
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES ();
INSERT INTO Steps_in_Recipe (step_id, recipe_id, instruction) VALUES ();
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES ();
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES ();
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES ();
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES ();
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES ();
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES ();
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES ();
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES ();
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES ();
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES ();
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES ();
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES ();
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES ();
INSERT INTO Ingredients_in_Recipe (ingredient_id, recipe_id, quantity, unit) VALUES ();
*/